var myString;
var bool;
var myVar;
var array;
var numArray;
numArray = [1, 2, 3, 4, 5];
array = ['hello', 'world'];
myString = "Hello World".slice(0, 5);
bool = true;
//myVar=4;
myVar = "ghss";
console.log(bool);
console.log(numArray);
var stringNumTuple;
stringNumTuple = ['string', 12,];
console.log(stringNumTuple);
var myvoid = null;
console.log(myvoid);
var mynull = null;
console.log(mynull);
var myundefined = undefined;
console.log(myundefined);
